version: '2'
services:
  postgres:
    image: postgres
    container_name: qddt_postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: qddt
      POSTGRES_USER: qddt
      POSTGRES_PASSWORD: qddt
    volumes:
      - e:\docker-data:/var/lib/postgresql/data
      
